controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

admin_dashboard:
    path: /admin
    controller: App\Controller\AdminController::dashboard